a=int(input("첫번째 숫자를 입력하세요"))
print('%s' %(a))
b=int(input("두번째 숫자를 입력하세요"))
print('%s' %(b))

a, b =map(int, input().split())

op1 = (a * ((b % 100) %10))
op2 = (a * ((b % 100) // 10))
op3 = (a * (b //100))
result = (op1+ op2*10 + op3*100)
print(op1)
print(op2)
print(op3)
print(result)